### ISSUE TITLE
warning of peer dependencies with angular 7

### ISSUE THREAD

**Issue by royanon** [drozhzhin-n-e/ngx-pinch-zoom#12]
When use with angular 7, npm install with the following dependencies warning.
Everything work fine except these warning.

npm WARN ngx-pinch-zoom@1.2.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-pinch-zoom@1.2.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by drozhzhin-n-e** [comment]
@royanon The latest version of the library has been updated to Angular 7
