### ISSUE TITLE
pixelated image IOS ISSUE

### ISSUE THREAD

**Issue by AmineMediazain** [drozhzhin-n-e/ngx-pinch-zoom#13]
Hey everyone,

I'm using this module to zoom a pdf component, I customize the core of the module and its work on Android devices but I get an issue with ios devices.

Why does the image quality get pixelated when zoomed in just on ios devices ?

**Comment by drozhzhin-n-e** [comment]
Hello. Can you record video?

**Comment by AmineMediazain** [comment]
yes of course, when can i sent it ?

**Comment by drozhzhin-n-e** [comment]
@AmineMediazain can send it to me by mail

**Comment by drozhzhin-n-e** [comment]
@AmineMediazain  This problem is related to drawing the canvas. If you set canvas width in styles, then in IOS you can’t get the original image size. Try not to change the width of the canvas, but use `transform: scale`

```
canvas {
    transform: scale(0.3);
    transform-origin: left top;
}
```

**Comment by AmineMediazain** [comment]
That's true man, the pdf file  is ok now
But the problem now  that the area of zoom is too big and the the swipe to
left is broken

**Comment by drozhzhin-n-e** [comment]
@AmineMediazain Yes, this is a problem. I think it's a matter of scaling the canvas. https://stackoverflow.com/questions/9742131/scaling-canvas-element-with-static-resolution

**Comment by AmineMediazain** [comment]
can you do me this favor and fix it for me,  i have problem with it

**Comment by drozhzhin-n-e** [comment]
@AmineMediazain I am afraid it is not. Try to talk about the problem here https://github.com/VadimDez/ng2-pdf-viewer/issues

**Comment by AmineMediazain** [comment]
hey man,
No one has answered me, i'm in trouble now

**Comment by drozhzhin-n-e** [comment]
@AmineMediazain  I'm sorry, maybe someone will answer later. But I can not help you, this is not a problem of pinch-zoom

**Comment by AmineMediazain** [comment]
Thank you anyway you did your best
