### ISSUE TITLE
Error: Cannot read property 'clientY' of undefined

### ISSUE THREAD

**Issue by Bandcy** [drozhzhin-n-e/ngx-pinch-zoom#14]
In state of zoom out, can't read property 'clientY' error occur when drag pinch-zoom element by touch
In state of zoom in, there is no error.

even event error occurred, the module working properly.

-- my environment
angular: 7.1
ngx-pinch-zoom: 1.2.1
multi-touchable monitor on windows 10

**Comment by drozhzhin-n-e** [comment]
@Bandcy Could you record a video?

**Comment by Bandcy** [comment]
https://youtu.be/Z7JpYDwIvh4

my html
<pinch-zoom [height]="100" [zoom-button]="true" [linear-horizontal-swipe]="true">
  <div>
    <table style="border-collapse: collapse;">
    ... some stuff
    </table>
  </div>
</pinch-zoom>

**Comment by drozhzhin-n-e** [comment]
@Bandcy  how do you scale the image? For scaling, you need two touch points on the screen, but you have only one point.

**Comment by drozhzhin-n-e** [comment]
@Bandcy thank. Soon the fix will be available in the npm library.
