### ISSUE TITLE
Disable behavior on non-mobile devices?

### ISSUE THREAD

**Issue by weatherbell** [drozhzhin-n-e/ngx-pinch-zoom#15]
Hi,
Great job with this component. Is it possible to disable the behavior entirely on non-mobile devices? The issue that I have with desktop devices is that the component prevents drag/drop functionality (the ability to save an image by dragging it to your desktop). Thanks!

**Comment by drozhzhin-n-e** [comment]
Hello. Now there is no way to disable it. But I will do it in the future.

**Comment by drozhzhin-n-e** [comment]
Hello. You can use the `disabled` property to disable the library.
