### ISSUE TITLE
Custom Zoom Level

### ISSUE THREAD

**Issue by apleshakov88** [drozhzhin-n-e/ngx-pinch-zoom#16]
Hi! Cool component!
But I didn't find a way how to apply custom scale - initial = 1, zoomed = 2.
Maybe you can add 1 more @Input() scaleRate parameter, to configure that?
Then replace 468 line to
`this.scale = this.initialScale * this.scaleRate;`

**Comment by drozhzhin-n-e** [comment]
@apleshakov88 Hey. Do you want to customize the scale for which event? When scaling with a button or double tap?

**Comment by apleshakov88** [comment]
Yep, for button.  I can use doubleTapScale for double tap. So it would be great to have similar solution for button instead of hardcoded   * 2. 
Many thanx

**Comment by drozhzhin-n-e** [comment]
yes, I agree. I will do it.

**Comment by apleshakov88** [comment]
Thanx! И удачи в дальнейшем!!!

**Comment by drozhzhin-n-e** [comment]
@apleshakov88  Спасибо!

**Comment by Xample** [comment]
@drozhzhin-n-e In the same state of mind, I would even suggest something like: min-zoom: 0.5, max-zoom: 1 (I need to have a smaller zoom in the beginning)

**Comment by drozhzhin-n-e** [comment]
To set the scaling factor for double tap, use the `double-tap-scale` property. Zoom factor for the zoom button: `zoomControlScale`

**Comment by drozhzhin-n-e** [comment]
@Xample You can set the original size of the image by resizing the container. Set the `overflow` property so that the container does not limit the image when scaling.

<div class="container" style="overflow: hidden">
    <pinch-zoom overflow="visible" style="width: ...; height: ...">
</div>
