### ISSUE TITLE
Is it possible to get info if image zoomed in?

### ISSUE THREAD

**Issue by dmelnyk23** [drozhzhin-n-e/ngx-pinch-zoom#17]
Is it possible to get info if image zoomed in? Also want to say THANK YOU, Great component!!!

**Comment by drozhzhin-n-e** [comment]
@dmelnyk23 thank! You can subscribe to the event https://github.com/drozhzhin-n-e/ngx-pinch-zoom#events For example "ptnch". This event returns `scale` parameter.
