### ISSUE TITLE
Reset default parameters of zoom and default image properties

### ISSUE THREAD

**Issue by kBorderon** [drozhzhin-n-e/ngx-pinch-zoom#18]
Hi, 

I'm using your technology but i'm blocked to apply it on a gestion map. I can't reset the default view of my image (no zoom apply, center image, no click point)  and the default level of zoom when I change the level of my map.

When I swap the level, I want to comeback to the default parameters but I can't because when I realised a single moovement (pan, click, pinch) the screen use the latest touch point (when i've zoomed the latest time) to zoom and set the next level of zoom.  Can you give me one tip to reset the default parameters ? 

Thank you in advance, cordially

**Comment by drozhzhin-n-e** [comment]
@kBorderon hello, try resetScale() https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom/pinch-zoom.component.ts#L483

**Comment by kBorderon** [comment]
Hi, thank you for all, i've find a way to resolve my problem because of bad using viewchild, now everything is working, thank you very much, cordially.
