### ISSUE TITLE
Mobile rendering issue

### ISSUE THREAD

**Issue by prasadchitale** [drozhzhin-n-e/ngx-pinch-zoom#2]
Hi!

Your demo link is working fine on a mobile. However a new project created using your component is not working properly on mobile devices.

Can you please share the source code of your demo link?

Regards

**Comment by drozhzhin-n-e** [comment]
@prasadchitale The source code of the sample does not differ from the code published on the githab. What problem do you have?

**Comment by prasadchitale** [comment]
If I use the published code as is then image rendering is not proper inside mobile browser. Also the image is top aligned instead of centre as shown in the demo.
My code snippet is as follows
<pinch-zoom height="100%">
    <div style="display: flex; height: 100%; align-items: center; justify-content: center;"> 
  <img src="{{path_to_image}}" /> 
  </div>
  
</pinch-zoom>

**Comment by drozhzhin-n-e** [comment]
@prasadchitale this div is added automatically `<div style="display: flex; height: 100%; align-items: center; justify-content: center;"></div>`, this code is enough: `<pinch-zoom height="100%"><img src="{{path_to_image}}" /></pinch-zoom>`. Pay attention to the height of the container. Try setting the height in pixels.

**Comment by prasadchitale** [comment]
I tried it. It still shows differently on Safari browser on iPhone. The zoom doesn't grows vertically. However the demo works perfectly on safari browser on iphone

**Comment by drozhzhin-n-e** [comment]
@prasadchitale have you solved this problem?

**Comment by andrixb** [comment]
Hi, 
I write that here cause I believe there's a sort of relationship with this issue and the one I'm facing:

I've got a list of pages which are made up of images as a background.
When I pinch to zoom in one of the pages I can neither keep the new center once the image has been dragged nor keep the actual center where I zoomed in.

That's the code I'm using:
```
<div class="document-container__listContainer">
        <pinch-zoom class="js-document-page" (events)="handlePinchZoomEvents($event)">
            <ul class="document-container__listWrapper" #jsPagesWrapper>
                <li class="document-container__page"
                    *ngFor="let page of Pages">
                    <my-page [page]="page"></my-page>
                </li>
            </ul>
        </pinch-zoom>
</div>
```

Many thanks

**Comment by drozhzhin-n-e** [comment]
@andrixb Hi. ngx-pinch-zoom can only scale the image, it does not support html scaling.

**Comment by andrixb** [comment]
@drozhzhin-n-e  thanks for the answer.
Maybe is a side effect, but it actually scales an HTML element because of the CSS properties applied.
The issue remains to find the centre cause it seems that the library considers the full height of my `ul` tag as it was the full image height.
Any suggestions regarding that (like how to recalculate the centre or so)?
Thanks :)

**Comment by drozhzhin-n-e** [comment]
@andrixb Try to return the height of your block instead of the image height here

https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom/pinch-zoom.component.ts#L335

**Comment by andrixb** [comment]
@drozhzhin-n-e don't know if it is useful for you but I made some tests and I created a PR with only a bunch of small suggestions you may test and use to extend your library. Currently, it allows using a more extensive set of HTML tags.
I personally tested it by using either a div tag and a ul tag.
Thanks

**Comment by drozhzhin-n-e** [comment]
@andrixb great! I will definitely look. Thanks for the help
