### ISSUE TITLE
Unable to wrap img with remote URL

### ISSUE THREAD

**Issue by AbhishekJ01** [drozhzhin-n-e/ngx-pinch-zoom#22]
I have a requirement to zoom my container with certain html inside it, I've a image in that container which loads from remote URL, When I wrap the image inside <pinch-zoom> it throws error.

Try this ,
```
<pinch-zoom>
    <img src="https://www.w3schools.com/images/w3schools_green.jpg" />
  </pinch-zoom>
```

**Comment by drozhzhin-n-e** [comment]
@AbhishekJ01 This repository also uses an image from a remote server https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/app.component.html Hardly a problem with pinch zoom. What error are you getting?

**Comment by AbhishekJ01** [comment]
Hey @drozhzhin-n-e Yeah its working with a remote URL as well. 

I have a *ngIf condition in my <img> tag that was causing an error I guess, once I removed that I'm able to zoom. Thanks a lot for your quick reply.

Appreciate it.
