### ISSUE TITLE
Not building when installing from github repo

### ISSUE THREAD

**Issue by emillime** [drozhzhin-n-e/ngx-pinch-zoom#23]
I am trying to fork this repo and installing the forked repo with npm (`npm i emillime/ngx-pinch-zoom`). When doing this it does not seem to build the library. Maybe adding a `postinstall` script would help?
I tried to add that myself but even after building manually I get the error `Cannot find module 'ngx-pinch-zoom'.`
Any help with this? How are you supposed to use it when installing from a Github repo?

**Comment by drozhzhin-n-e** [comment]
Configure import of the module from the folder `import { PinchZoomModule } from './pinch-zoom/pinch-zoom.module';`
