### ISSUE TITLE
Possible disable the zoom?

### ISSUE THREAD

**Issue by MikeMilian** [drozhzhin-n-e/ngx-pinch-zoom#26]
Is it possible to lock/disable the zoom? 

I am creating a drawing app, and the zoom works great with the canvas. But when you zoom, you also draw. I like to lock the zoom when drawing.

**Comment by MikeMilian** [comment]
Hello? Any response wil be apprenticed.

**Comment by drozhzhin-n-e** [comment]
@MikeMilian hello. Use <pinch-zoom [disabled] = "true">

**Comment by drozhzhin-n-e** [comment]
But first upgrade to version 1.2.5

**Comment by MikeMilian** [comment]
Yes great! Thank you very much!
