### ISSUE TITLE
ViewChild doen't work with angular 8 ivy

### ISSUE THREAD

**Issue by dsantosbfs** [drozhzhin-n-e/ngx-pinch-zoom#29]
Angular 8.1.2 running with Ivy broken the component and always show de message below:

Cannot read property 'getElementsByTagName' of undefined

In debugger, this message is related with line 426 of builded ngx-pinch-zoom component.

Search in web I have found the correct configuration for ViewChild selector:

@ViewChild('content', {static: true}) contentElement: ElementRef;

Actualy, the declaration is:

@ViewChild('content') contentElement: ElementRef;

Reference: https://angular.io/guide/static-query-migration

**Comment by drozhzhin-n-e** [comment]
Thanks. This is fixed in new versions of the library.
