### ISSUE TITLE
Limit Zoom

### ISSUE THREAD

**Issue by TheOriginalVirus** [drozhzhin-n-e/ngx-pinch-zoom#3]
Hey!

I was wondering if it is possible to limit the amount of zoom (Also if there is, how would one achieve this?)

Thank you :D

**Comment by drozhzhin-n-e** [comment]
@TheOriginalVirus currently, there is no such possibility, but I will add it in the future

**Comment by amartinez2706** [comment]
Any updates on this?

**Comment by drozhzhin-n-e** [comment]
@amartinez2706 Unfortunately, now there is no time

**Comment by drozhzhin-n-e** [comment]
@TheOriginalVirus @amartinez2706 You can use the `limit-zoom` property  https://github.com/drozhzhin-n-e/ngx-pinch-zoom/commit/4b0db97ecb3cd780a6f960ee222a64291fe4e120

**Comment by amartinez2706** [comment]
@TheOriginalVirus  thanks for the fix :)
