### ISSUE TITLE
pinch-zoom within scrollable container

### ISSUE THREAD

**Issue by considine** [drozhzhin-n-e/ngx-pinch-zoom#33]
When you have a pinch-zoom element within a scrollable container, you can get some unexpected behavior. If you zoom in and then drag down you'll be restricted vertically prior to getting to the bottom of the image. That's because pinch-zoom prevents default on swipe so the image wont scroll down within its container. You need to zoom out, scroll down, then zoom back in

**Comment by drozhzhin-n-e** [comment]
@considine Thank!
