### ISSUE TITLE
Events on body don't stop listen after destroy component

### ISSUE THREAD

**Issue by Rockstar311** [drozhzhin-n-e/ngx-pinch-zoom#39]
In chrome after destroying component, I can't select some text on the page. After research I found that after destroy component of pinch-zoom, on element <body> events don't stop listening. So on <body> we still have event mousemove and with this event we can't select a text on a page

**Comment by Rockstar311** [comment]
I was found a solution to fix the selection of text, on destroying your component need call method from deep  `this.pinchZoomComponent.pinchZoom.touches.destroy();`

**Comment by drozhzhin-n-e** [comment]
I will try to fix the problem with text selection. In the latest version of the component, unsubscribing from mouse events occurs automatically.

https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom/pinch-zoom.component.ts#L103
