### ISSUE TITLE
how to specify the amount of zoom when double tapped

### ISSUE THREAD

**Issue by kshantanu94** [drozhzhin-n-e/ngx-pinch-zoom#4]
Hi, 

what are the values that need to be changed to increase/decrease the amount of zoom that happens on double tap? 

PS. I've purchased the premium version of pinch zoom

**Comment by drozhzhin-n-e** [comment]
Hi, thanks for supporting the project. This option will be in the future. You can change the zoom ratio here: https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom/pinch-zoom.component.ts#L397 

for example:
`this.scale = this.initialScale * 3;
this.moveX = this.initialMoveX - (changedTouches[0].clientX * 2 - this.elementPosition.left);
this.moveY = this.initialMoveY - (changedTouches[0].clientY * 2 - this.elementPosition.top);`

**Comment by kshantanu94** [comment]
but this doesn't center the newly zoomed canvas properly, does it?

**Comment by drozhzhin-n-e** [comment]
@kshantanu94 what coefficient do you want to use for scaling?

**Comment by hitmacreed** [comment]
how about pdf support i made something for ng2-pdf-viewer but this one seems better [here](https://github.com/hitmacreed/ng2-pdf-viewer-zoom-in-and-out-pinchZoom-Ionic-3/blob/master/README.md)

**Comment by drozhzhin-n-e** [comment]
https://github.com/drozhzhin-n-e/ngx-pinch-zoom/commit/3f6d438e442dd33007f18c14273329b0b953d8ca
