### ISSUE TITLE
Error: Can't resolve 'core-js/proposals/reflect-metadata'

### ISSUE THREAD

**Issue by PlanB007** [drozhzhin-n-e/ngx-pinch-zoom#43]
When installing the package and added it to my module & HTML file. The following error pops up when building:

`Error: Can't resolve 'core-js/proposals/reflect-metadata'`

I'm using the latest version of `ngx-pinch-zoom` and Angular. If you need futher information, please let me know!

**Comment by drozhzhin-n-e** [comment]
Do you mean Angular 8.3.21?

**Comment by PlanB007** [comment]
It was on 8.2.14 after reinstall the package, it worked. Not sure what caused the problem
