### ISSUE TITLE
Can you have two images inside <pinch-zoom> one under the other?

### ISSUE THREAD

**Issue by ryankempster** [drozhzhin-n-e/ngx-pinch-zoom#5]
`<pinch-zoom>
  <img class="image" src={{url}}>
  <img class="image" src={{url}}>
</pinch-zoom>`

It seems like with this, the two images will be positioned next to each other due to display: flex, and disabling it breaks the zoom (it'll zoom into the centre instead of where you tap). Any fixes?

**Comment by ryankempster** [comment]
I tried this, it makes it so that if you zoom in it'll only zoom to the centre of the div and not where you click

**Comment by considine** [comment]
@ryankempster did you end up figuring this out?
