### ISSUE TITLE
get zoom state?

### ISSUE THREAD

**Issue by Simbaclaws** [drozhzhin-n-e/ngx-pinch-zoom#52]
Hey there,

Apparently it's possible to toggle the zoom programmatically depending on the current state.
What If I only want to zoom out whenever it's zoomed in on a specific action?

Can I somehow get the current zoom state (zoomed in, or zoomed out)?

I find it quite strange that there is only a toggle and not for example a zoomOut and zoomIn. Or at least a state to determine when to toggle.

Can I just check for the class pz-dragging?

**Comment by Simbaclaws** [comment]
Apparently checking for pz-dragging on the pinch-zoom div child works.

**Comment by drozhzhin-n-e** [comment]
@Simbaclaws What you are talking about is in the Pro version. You can make a subscription to the state change. More details here: http://ivylab.space/pinch-zoom
