### ISSUE TITLE
Handle start touch event and finish touch event.

### ISSUE THREAD

**Issue by klochko7** [drozhzhin-n-e/ngx-pinch-zoom#56]
Good day! I try to handle touch event but nothing happend. Could anyone help please.

```
        <pinch-zoom (events)="handlePinchZoomEvents($event)">
          <img src="{{url}}">
        </pinch-zoom>
```

```
  handlePinchZoomEvents(event) {
    console.log("handlePinchZoomEvents", event);
  }
```

**Comment by drozhzhin-n-e** [comment]
@klochko7 Hey. Are you using the Pro version?

**Comment by klochko7** [comment]
**drozhzhin-n-e**, I am using Free version.

**Comment by drozhzhin-n-e** [comment]
@klochko7 Please note that events are available only in the Pro version http://ivylab.space/pinch-zoom.

**Comment by klochko7** [comment]
**drozhzhin-n-e**, thanks, I understand. If there is a free way to listen when image stop resized?

**Comment by drozhzhin-n-e** [comment]
@klochko7 I am afraid it is not
