### ISSUE TITLE
Fit html content

### ISSUE THREAD

**Issue by teland94** [drozhzhin-n-e/ngx-pinch-zoom#63]
I have issue when I put into component html content img and rectangles over it. Can all of this fit to 100% width like img?

**Comment by drozhzhin-n-e** [comment]
@teland94 Hello. You have published the Pro version of this library in the public domain on your stackblitz account. I ask you to remove the code from the public domain.

**Comment by teland94** [comment]
> @teland94 Hello. You have published the Pro version of this library in the public domain on your stackblitz account. I ask you to remove the code from the public domain.

Hello. I have removed it.

**Comment by drozhzhin-n-e** [comment]
Thank you
