### ISSUE TITLE
sluggish scroll on cordova

### ISSUE THREAD

**Issue by zivlevy** [drozhzhin-n-e/ngx-pinch-zoom#7]
when using in a cordova app on an Iphone, the scrolling is very sluggish.
In other components of the application, where scrolling is needed, I add:
-webkit-overflow-scrolling: touch;
to the css of the container where scroll is needed and then scrolling is smooth.

Can you advice how to over come the issue in ngx-pinch-zoom?

**Comment by drozhzhin-n-e** [comment]
@zivlevy please specify how you use ngx-pinch-zoom? To scale an image? You mean scrolling inside the <pinch-zoom>?

**Comment by zivlevy** [comment]
I use it as in your example:
`<pinch-zoom>
<img [src]="img" alt="" >
</pinch-zoom>`

when I pinch out for zoom in - the image getting bigger as needed but in a sluggish "steps", then scrolling is sluggish as well.

as said it is when working on iOS with cordova.

**Comment by drozhzhin-n-e** [comment]
I think I understood what you mean. But it would be great if you recorded the problem on video. First, I would suggest checking the speed of the animation `transform: matrix` on any other element

**Comment by zivlevy** [comment]
will record and upload later today.
Notice that such sluggish scrolling happens also on the following setup:
`<div id="wrapper" style="overflow: scroll"`>
<img [src]="img' style="width: 1000px">
</div>'
but when I add `-webkit-overflow-scrolling: touch;` to the wrapping div scrolling is smooth.
So i am looking on a way to add it to the <pinch-zoom> directive.

**Comment by AtanasChachev** [comment]
@drozhzhin-n-e can that <pinch-zoom> component be used for content but not only for images? Because when I paste some image , it attaches the `pz-dragging` class , but when I remove the image and leave some content , it doesn't work.. how can I use it not only for an image but for a whole container with content inside ? :(

**Comment by AtanasChachev** [comment]
@drozhzhin-n-e It's me here again, after digging a little bit in the plugin , wouldn't be good if you add an option to take the [0] div or [0] img based on lets say some custom attribute let's say [zoomableTarget]="img" or div ? It works with (div)[0] and if it's height: 100% and width: 100% the whole content area is zoomable , which is good in my opinion for the comment above I've posted ^^

**Comment by drozhzhin-n-e** [comment]
@zivlevy I watched the video. I recommend checking the speed of the animation `transform: matrix` on any other element. If the problem persists, it is unlikely that it will be possible to solve by changing the ngx-pinch-zoom.

**Comment by zivlevy** [comment]
the problem is not whit transform: matrix speed.
When i double tap the transformation is quick (both on zoom in and zoom
out).
Also when I change the matrix parameters on the developer console by hand
the transformation is quick and smooth.
The problem seems to be on the pinch recognition that is slow somehow.

**Comment by zivlevy** [comment]
I found a cure ...
Strange but all works fine when compiling the angular project with the —prod flag.
Didn’t get to the bottom of it, but all is good now.
@drozhzhin-n-e a thanks for your prompt support.

**Comment by drozhzhin-n-e** [comment]
@zivlevy thank you for finding a solution
