### ISSUE TITLE
Fullscreen image

### ISSUE THREAD

**Issue by NePheus** [drozhzhin-n-e/ngx-pinch-zoom#74]
Is it possible to show an image in fullscreen, i.e. cut off on the left and the right, like the css attribute 'object-fit: cover', but access this hidden parts by pinching/dragging? Object-fit is not working as well as centered flex layout, where the image container is overflowed of the window view on the x-axis. Is there any other approach to implement this?

**Comment by iCantWriteCode** [comment]
@NePheus  I have the same issue did you find this out?
