### ISSUE TITLE
Event zoom-in and zoom out not working

### ISSUE THREAD

**Issue by andrew-pakula** [drozhzhin-n-e/ngx-pinch-zoom#79]
Hi. I am using pro version.I have subscription events in my code, and retrieve only touchend event.

`<pinch-zoom
    (events)="handlePinchZoomEvents($event)"
    listeners="auto"
>
    <img (click)="gallerized.emit(true)" [src]="src" alt="Produkt"/>

</pinch-zoom>

`    handlePinchZoomEvents(event: any) {
        console.log(event);  {name: "touchend", detail: undefined} 
                                            
    }
`

**Comment by drozhzhin-n-e** [comment]
Hello. Does everything else work fine?

**Comment by andrzej-pakula** [comment]
Yes, otherwise it's ok, but the zoom in zoom out event doesn't work. I managed without them.

**Comment by playground** [comment]
It's not working for me too, how do you listen to an event?  want to be able to determine scale factor and the mouse position on the image.
