### ISSUE TITLE
Detect image clientWidth and clientHeight during pinch event.

### ISSUE THREAD

**Issue by klochko7** [drozhzhin-n-e/ngx-pinch-zoom#9]
**drozhzhin-n-e** , good day ! I am trying to use your ngx-pinch-zoom … it working perfectly. But above the image I draw html span with special coordinates … something like hot spots … Is it possible to detect image clientWidth and clientHeight during pinch event for redrawing hot spots according image scale ?

**Comment by drozhzhin-n-e** [comment]
@klochko7 Hello. You can modify the EventEmitter: https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom/pinch-zoom.component.ts#L294 

eg:
`this.events.emit({ type: 'pinch', scale: this.scale });`

after that subscribe to events:
`<pinch-zoom (events)="myHandleEvents($event)"></pinch-zoom>`

**Comment by klochko7** [comment]
**drozhzhin-n-e**, I modify the EventEmitter at ngx-pinch-zoom.js

   ```
 handlePinch(event) {
        event.preventDefault();
        let /** @type {?} */ touches = event.touches;
        if (!this.eventType) {
            this.initialDistance = this.getDistance(touches);
            this.moveXC = (((event.touches[0].clientX - this.elementPosition.left) + (event.touches[1].clientX - this.elementPosition.left)) / 2) - this.initialMoveX;
            this.moveYC = (((event.touches[0].clientY - this.elementPosition.top) + (event.touches[1].clientY - this.elementPosition.top)) / 2) - this.initialMoveY;
        }
        this.eventType = 'pinch';
        this.events.emit({ type: 'pinch', scale: this.scale });
        this.distance = this.getDistance(touches);
        this.scale = this.initialScale * (this.distance / this.initialDistance);
        this.moveX = this.initialMoveX - (((this.distance / this.initialDistance) * this.moveXC) - this.moveXC);
        this.moveY = this.initialMoveY - (((this.distance / this.initialDistance) * this.moveYC) - this.moveYC);
        this.transformElement(0);
    }
```

```
          <pinch-zoom class="" (events)="handlePinchZoomEvents($event)">

          </pinch-zoom>
```

```
  handlePinchZoomEvents(event){

    console.log("handlePinchZoomEvents",event);
  }
```

How to get value in my Ionic 3 project ?

**Comment by drozhzhin-n-e** [comment]
try moving row below:

```
...
this.scale = this.initialScale * (this.distance / this.initialDistance);
this.events.emit({ type: 'pinch', scale: this.scale });
```

**Comment by drozhzhin-n-e** [comment]
You made changes to node_modules/ngx-pinch-zoom? Try to take code from this repository.

**Comment by klochko7** [comment]
I changed file from \node_modules\ngx-pinch-zoom\fesm2015\ngx-pinch-zoom.js

**Comment by drozhzhin-n-e** [comment]
I recommend to take the code from this repository.

**Comment by drozhzhin-n-e** [comment]
@klochko7 hello. Download pinch-zoom from here: https://github.com/drozhzhin-n-e/ngx-pinch-zoom/tree/master/src/app/pinch-zoom and transfer to the /src/app/ folder of your project. Then  update the import in your module:
`import { PinchZoomModule } from 'ngx-pinch-zoom'; `
change to:
`import { PinchZoomModule } from './pinch-zoom/pinch-zoom.module'; `

**Comment by klochko7** [comment]
**drozhzhin-n-e**, thanks a lot. I copy folder pinch-zoom and paste it to **\src\app**. Update the import in my module. But now I have build error. I will try to find solution.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND 
file:///android_asset/www/pinch-zoom.component.css 
```
`
polyfills.js:3 Unhandled Promise rejection: Failed to load pinch-zoom.component.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load pinch-zoom.component.css undefined`

**Comment by drozhzhin-n-e** [comment]
@klochko7 I can only suggest copying styles from pinch-zoom.component.css to your style file.

**Comment by klochko7** [comment]
**drozhzhin-n-e**, good day!  Unfortunately I have another build problem and changes to pinch-zoom.component in node_modules not being reflected. Can you modify please the EventEmitter in future release and add additional value for developers ?

**Comment by drozhzhin-n-e** [comment]
@klochko7 ok, I will do it

**Comment by klochko7** [comment]
**drozhzhin-n-e**, Thank you very much. I subscribe to this project.
